### ISSUE TITLE
Bug: circular setting is ignored when reevaluate is set

### ISSUE THREAD

**Issue by nrsimha** [livibetter-backup/jquery-jknav#2]
When both circular and reevaluate is set, circular is being ignored.

**Comment by nrsimha** [comment]
Here is a fix: #3 (Use circular setting when reevaluate is set.)

**Comment by livibetter** [comment]
I've not been touch the code for long time, so could you point out what exactly the bug is and the expected result using the demo page, if possible, which should be j/k keys (both settings are true).

I can see if I have circular off and reevaluate on, it's still being circular, is that the bug? If so, you fix doesn't seem to fix it.

**Comment by nrsimha** [comment]
I removed .min.js file from pull request.

Yes, bug is that when `circular: false` and `reevaluate: true` it still behaves like circular.

I tried in demo by adding `circular: false` setting on line 40: `$.jknav.init({name: 'h2h3', circular: false, reevaluate: true});`And everything works nicely.

Make sure `circular: false` is set as defaults are `circular: true`. 

May I updated it in demo file?

**Comment by livibetter** [comment]
I forgot the patch is on branch, my bad.

Yes, you can go ahead update the demo, but by adding an extra pair of keys for that settings pick one you think make senses, don't override the j/k and make sure you also add the key pair to the div on top/right.

Stack the commit on #3, I will squash them.

**Comment by nrsimha** [comment]
Added it to the demo (keys: n, m).

**Comment by livibetter** [comment]
Thanks for all your work!
